# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Web_Scrapper_Generic_UI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(759, 485)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(530, 10, 221, 361))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.status_msgs_listWidget = QtGui.QListWidget(self.groupBox)
        self.status_msgs_listWidget.setGeometry(QtCore.QRect(10, 20, 201, 321))
        self.status_msgs_listWidget.setObjectName(_fromUtf8("status_msgs_listWidget"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 260, 301, 111))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 281, 71))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.start_crawling_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.start_crawling_pushButton.setObjectName(_fromUtf8("start_crawling_pushButton"))
        self.gridLayout_2.addWidget(self.start_crawling_pushButton, 1, 0, 1, 1)
        self.stop_crawling_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.stop_crawling_pushButton.setObjectName(_fromUtf8("stop_crawling_pushButton"))
        self.gridLayout_2.addWidget(self.stop_crawling_pushButton, 2, 0, 1, 1)
        self.save_crawled_links_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.save_crawled_links_pushButton.setObjectName(_fromUtf8("save_crawled_links_pushButton"))
        self.gridLayout_2.addWidget(self.save_crawled_links_pushButton, 1, 1, 1, 1)
        self.data_extraction_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.data_extraction_pushButton.setObjectName(_fromUtf8("data_extraction_pushButton"))
        self.gridLayout_2.addWidget(self.data_extraction_pushButton, 2, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 260, 121, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 21, 101, 71))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.absolute_url_radioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.absolute_url_radioButton.setObjectName(_fromUtf8("absolute_url_radioButton"))
        self.verticalLayout.addWidget(self.absolute_url_radioButton)
        self.relative_url_radioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.relative_url_radioButton.setObjectName(_fromUtf8("relative_url_radioButton"))
        self.verticalLayout.addWidget(self.relative_url_radioButton)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 511, 101))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 491, 61))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.url_pattern_lineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.url_pattern_lineEdit.setObjectName(_fromUtf8("url_pattern_lineEdit"))
        self.gridLayout.addWidget(self.url_pattern_lineEdit, 1, 1, 1, 1)
        self.url_lineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.url_lineEdit.setText(_fromUtf8(""))
        self.url_lineEdit.setObjectName(_fromUtf8("url_lineEdit"))
        self.gridLayout.addWidget(self.url_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.file_name_lineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.file_name_lineEdit.setObjectName(_fromUtf8("file_name_lineEdit"))
        self.gridLayout.addWidget(self.file_name_lineEdit, 0, 4, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.layoutWidget2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 1, 2, 1, 1)
        self.main_progressBar = QtGui.QProgressBar(self.centralwidget)
        self.main_progressBar.setGeometry(QtCore.QRect(10, 390, 741, 41))
        self.main_progressBar.setProperty("value", 0)
        self.main_progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.main_progressBar.setObjectName(_fromUtf8("main_progressBar"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 110, 511, 151))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.crawled_links_listWidget = QtGui.QListWidget(self.centralwidget)
        self.crawled_links_listWidget.setGeometry(QtCore.QRect(20, 130, 491, 111))
        self.crawled_links_listWidget.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.crawled_links_listWidget.setTabKeyNavigation(True)
        self.crawled_links_listWidget.setDragEnabled(True)
        self.crawled_links_listWidget.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.crawled_links_listWidget.setAlternatingRowColors(True)
        self.crawled_links_listWidget.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.crawled_links_listWidget.setObjectName(_fromUtf8("crawled_links_listWidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 759, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad_Configuration_File = QtGui.QAction(MainWindow)
        self.actionLoad_Configuration_File.setObjectName(_fromUtf8("actionLoad_Configuration_File"))
        self.actionSave_Configuration_File = QtGui.QAction(MainWindow)
        self.actionSave_Configuration_File.setObjectName(_fromUtf8("actionSave_Configuration_File"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Configuration_File)
        self.menuFile.addAction(self.actionSave_Configuration_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Status Messages :", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Control:", None))
        self.start_crawling_pushButton.setText(_translate("MainWindow", "Start Crawling", None))
        self.stop_crawling_pushButton.setText(_translate("MainWindow", "Stop Crawling", None))
        self.save_crawled_links_pushButton.setText(_translate("MainWindow", "Save Crawled Links", None))
        self.data_extraction_pushButton.setText(_translate("MainWindow", "Data Extraction", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Crawling Method :", None))
        self.absolute_url_radioButton.setText(_translate("MainWindow", "Absolutre Url", None))
        self.relative_url_radioButton.setText(_translate("MainWindow", "Relative Url", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Links", None))
        self.label_2.setText(_translate("MainWindow", "Url Pattern", None))
        self.label.setText(_translate("MainWindow", "Url ", None))
        self.label_3.setText(_translate("MainWindow", "File name", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Crawled Links:", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad_Configuration_File.setText(_translate("MainWindow", "Load Configuration File", None))
        self.actionSave_Configuration_File.setText(_translate("MainWindow", "Save Configuration File ", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

